
import type { Metadata } from "next";
import { inter } from "@/assets/fonts/fonts";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Layout from "@/components/layout/Layout";
import Navbar from "@/components/navbar/Navbar";
import '@/lib/i18n';
import { TranslationProvider } from "@/components/translationProvieder/TranslationProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" >
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen `} 
      >
        <TranslationProvider>
          <Header />
          <main className="flex-grow" >
            <Layout>
              {children}
              <Navbar />
            </Layout>
          </main>
          <Footer />
        </TranslationProvider>
      </body>
    </html>
  );
}